# Generated by Django 2.2.4 on 2019-09-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(help_text='image size: width=283px height=283px', upload_to='profile_pics'),
        ),
    ]
