# Generated by Django 2.2.4 on 2019-08-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190825_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductHighlight',
        ),
    ]
