# Generated by Django 2.2.4 on 2019-08-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_brand_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='big_image',
            field=models.ImageField(blank=True, help_text='Image size: width=700 px height=700px', null=True, upload_to='products/big/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Image size: width=100px height=100px', null=True, upload_to='products/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(help_text='Image size: width=193px height=115px', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(blank=True, help_text='Image size: width=193px height=115px', null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Image size: width=265px height=290px', null=True, upload_to='products/'),
        ),
    ]
