# Generated by Django 2.2.4 on 2019-09-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190901_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Insert name to avoid confusion', max_length=100, null=True)),
                ('offer_image', models.ImageField(help_text='Image size: width: 401px height: 424px', upload_to='offers/')),
            ],
        ),
        migrations.CreateModel(
            name='SuperImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Insert name to avoid confusion', max_length=100, null=True)),
                ('super_image', models.ImageField(help_text='Image size: width: 401px height: 424px', upload_to='super/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(help_text='To select multiple colors, press CTRL and select.', related_name='product', to='product.Color'),
        ),
    ]
