# Generated by Django 2.2.4 on 2019-09-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_notification_product'),
        ('product', '0013_subscription'),
    ]

    operations = [
    ]
