# Generated by Django 2.2.4 on 2019-09-04 05:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0018_product_offer_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_tag',
            field=models.CharField(blank=True, help_text='E.g. 15% off', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('cart', models.ManyToManyField(related_name='orders', to='product.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
