# Generated by Django 2.2.4 on 2019-09-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190904_0744'),
        ('product', '0020_auto_20190904_1302'),
    ]

    operations = [
    ]
