# Generated by Django 2.2.4 on 2019-09-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_userrequestproduct_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_small_image',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_image',
        ),
    ]
