# Generated by Django 2.2.4 on 2019-09-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190912_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(help_text='Image size: width=1280px height=435px', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_content', to='product.SpecificationContent'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_title', to='product.SpecificationTitle'),
        ),
        migrations.AddField(
            model_name='specificationcontent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='product.SpecificationTitle'),
        ),
    ]
