# Generated by Django 2.2.4 on 2019-09-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190913_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Is this product available in stock?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Does you want this item to be displayed in offer section?'),
        ),
    ]
