# Generated by Django 2.2.4 on 2019-09-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190916_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='brand',
        ),
        migrations.AlterField(
            model_name='type',
            name='brand_type',
            field=models.CharField(help_text='E.g. Economic, Gaming, etc.', max_length=100),
        ),
    ]
