# Generated by Django 2.2.4 on 2019-09-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20190929_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutITeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
