# Generated by Django 2.2.4 on 2019-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_aboutiteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.BooleanField(default=True, verbose_name='Make this product visibile?'),
        ),
        migrations.AlterField(
            model_name='aboutiteam',
            name='logo',
            field=models.ImageField(help_text='Image size: width=192px height=31px', upload_to='logo/'),
        ),
    ]
