# Generated by Django 2.2.6 on 2020-01-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_aboutiteam_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutiteam',
            name='facebook_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutiteam',
            name='instagram_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutiteam',
            name='youtube_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
