# Generated by Django 2.2.6 on 2020-01-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200116_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutiteam',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='aboutiteam',
            name='contact1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutiteam',
            name='contact2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutiteam',
            name='contact3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
